# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='RectData',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\ndata.proto\x12\x08RectData\"]\n\x0bPictureData\x12\x0e\n\x06height\x18\x01 \x02(\x05\x12\r\n\x05width\x18\x02 \x02(\x05\x12/\n\x10object_parameter\x18\x03 \x03(\x0b\x32\x15.RectData.ObjectParam\"R\n\x0bObjectParam\x12\x0b\n\x03tag\x18\x01 \x03(\t\x12\x0c\n\x04xmin\x18\x02 \x02(\x05\x12\x0c\n\x04ymin\x18\x03 \x02(\x05\x12\x0c\n\x04xmax\x18\x04 \x02(\x05\x12\x0c\n\x04ymax\x18\x05 \x02(\x05')
)




_PICTUREDATA = _descriptor.Descriptor(
  name='PictureData',
  full_name='RectData.PictureData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='RectData.PictureData.height', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='RectData.PictureData.width', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='object_parameter', full_name='RectData.PictureData.object_parameter', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=117,
)


_OBJECTPARAM = _descriptor.Descriptor(
  name='ObjectParam',
  full_name='RectData.ObjectParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag', full_name='RectData.ObjectParam.tag', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='xmin', full_name='RectData.ObjectParam.xmin', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ymin', full_name='RectData.ObjectParam.ymin', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='xmax', full_name='RectData.ObjectParam.xmax', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ymax', full_name='RectData.ObjectParam.ymax', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=201,
)

_PICTUREDATA.fields_by_name['object_parameter'].message_type = _OBJECTPARAM
DESCRIPTOR.message_types_by_name['PictureData'] = _PICTUREDATA
DESCRIPTOR.message_types_by_name['ObjectParam'] = _OBJECTPARAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PictureData = _reflection.GeneratedProtocolMessageType('PictureData', (_message.Message,), {
  'DESCRIPTOR' : _PICTUREDATA,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:RectData.PictureData)
  })
_sym_db.RegisterMessage(PictureData)

ObjectParam = _reflection.GeneratedProtocolMessageType('ObjectParam', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTPARAM,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:RectData.ObjectParam)
  })
_sym_db.RegisterMessage(ObjectParam)


# @@protoc_insertion_point(module_scope)
