// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

#ifndef PROTOBUF_data_2eproto__INCLUDED
#define PROTOBUF_data_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace RectData {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_data_2eproto();
void protobuf_AssignDesc_data_2eproto();
void protobuf_ShutdownFile_data_2eproto();

class PictureData;
class ObjectParam;

// ===================================================================

class PictureData : public ::google::protobuf::Message {
 public:
  PictureData();
  virtual ~PictureData();

  PictureData(const PictureData& from);

  inline PictureData& operator=(const PictureData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PictureData& default_instance();

  void Swap(PictureData* other);

  // implements Message ----------------------------------------------

  PictureData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PictureData& from);
  void MergeFrom(const PictureData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 height = 1;
  inline bool has_height() const;
  inline void clear_height();
  static const int kHeightFieldNumber = 1;
  inline ::google::protobuf::int32 height() const;
  inline void set_height(::google::protobuf::int32 value);

  // required int32 width = 2;
  inline bool has_width() const;
  inline void clear_width();
  static const int kWidthFieldNumber = 2;
  inline ::google::protobuf::int32 width() const;
  inline void set_width(::google::protobuf::int32 value);

  // repeated .RectData.ObjectParam object_parameter = 3;
  inline int object_parameter_size() const;
  inline void clear_object_parameter();
  static const int kObjectParameterFieldNumber = 3;
  inline const ::RectData::ObjectParam& object_parameter(int index) const;
  inline ::RectData::ObjectParam* mutable_object_parameter(int index);
  inline ::RectData::ObjectParam* add_object_parameter();
  inline const ::google::protobuf::RepeatedPtrField< ::RectData::ObjectParam >&
      object_parameter() const;
  inline ::google::protobuf::RepeatedPtrField< ::RectData::ObjectParam >*
      mutable_object_parameter();

  // @@protoc_insertion_point(class_scope:RectData.PictureData)
 private:
  inline void set_has_height();
  inline void clear_has_height();
  inline void set_has_width();
  inline void clear_has_width();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 height_;
  ::google::protobuf::int32 width_;
  ::google::protobuf::RepeatedPtrField< ::RectData::ObjectParam > object_parameter_;
  friend void  protobuf_AddDesc_data_2eproto();
  friend void protobuf_AssignDesc_data_2eproto();
  friend void protobuf_ShutdownFile_data_2eproto();

  void InitAsDefaultInstance();
  static PictureData* default_instance_;
};
// -------------------------------------------------------------------

class ObjectParam : public ::google::protobuf::Message {
 public:
  ObjectParam();
  virtual ~ObjectParam();

  ObjectParam(const ObjectParam& from);

  inline ObjectParam& operator=(const ObjectParam& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ObjectParam& default_instance();

  void Swap(ObjectParam* other);

  // implements Message ----------------------------------------------

  ObjectParam* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ObjectParam& from);
  void MergeFrom(const ObjectParam& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string tag = 1;
  inline int tag_size() const;
  inline void clear_tag();
  static const int kTagFieldNumber = 1;
  inline const ::std::string& tag(int index) const;
  inline ::std::string* mutable_tag(int index);
  inline void set_tag(int index, const ::std::string& value);
  inline void set_tag(int index, const char* value);
  inline void set_tag(int index, const char* value, size_t size);
  inline ::std::string* add_tag();
  inline void add_tag(const ::std::string& value);
  inline void add_tag(const char* value);
  inline void add_tag(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& tag() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_tag();

  // required int32 xmin = 2;
  inline bool has_xmin() const;
  inline void clear_xmin();
  static const int kXminFieldNumber = 2;
  inline ::google::protobuf::int32 xmin() const;
  inline void set_xmin(::google::protobuf::int32 value);

  // required int32 ymin = 3;
  inline bool has_ymin() const;
  inline void clear_ymin();
  static const int kYminFieldNumber = 3;
  inline ::google::protobuf::int32 ymin() const;
  inline void set_ymin(::google::protobuf::int32 value);

  // required int32 xmax = 4;
  inline bool has_xmax() const;
  inline void clear_xmax();
  static const int kXmaxFieldNumber = 4;
  inline ::google::protobuf::int32 xmax() const;
  inline void set_xmax(::google::protobuf::int32 value);

  // required int32 ymax = 5;
  inline bool has_ymax() const;
  inline void clear_ymax();
  static const int kYmaxFieldNumber = 5;
  inline ::google::protobuf::int32 ymax() const;
  inline void set_ymax(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:RectData.ObjectParam)
 private:
  inline void set_has_xmin();
  inline void clear_has_xmin();
  inline void set_has_ymin();
  inline void clear_has_ymin();
  inline void set_has_xmax();
  inline void clear_has_xmax();
  inline void set_has_ymax();
  inline void clear_has_ymax();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> tag_;
  ::google::protobuf::int32 xmin_;
  ::google::protobuf::int32 ymin_;
  ::google::protobuf::int32 xmax_;
  ::google::protobuf::int32 ymax_;
  friend void  protobuf_AddDesc_data_2eproto();
  friend void protobuf_AssignDesc_data_2eproto();
  friend void protobuf_ShutdownFile_data_2eproto();

  void InitAsDefaultInstance();
  static ObjectParam* default_instance_;
};
// ===================================================================


// ===================================================================

// PictureData

// required int32 height = 1;
inline bool PictureData::has_height() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PictureData::set_has_height() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PictureData::clear_has_height() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PictureData::clear_height() {
  height_ = 0;
  clear_has_height();
}
inline ::google::protobuf::int32 PictureData::height() const {
  // @@protoc_insertion_point(field_get:RectData.PictureData.height)
  return height_;
}
inline void PictureData::set_height(::google::protobuf::int32 value) {
  set_has_height();
  height_ = value;
  // @@protoc_insertion_point(field_set:RectData.PictureData.height)
}

// required int32 width = 2;
inline bool PictureData::has_width() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PictureData::set_has_width() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PictureData::clear_has_width() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PictureData::clear_width() {
  width_ = 0;
  clear_has_width();
}
inline ::google::protobuf::int32 PictureData::width() const {
  // @@protoc_insertion_point(field_get:RectData.PictureData.width)
  return width_;
}
inline void PictureData::set_width(::google::protobuf::int32 value) {
  set_has_width();
  width_ = value;
  // @@protoc_insertion_point(field_set:RectData.PictureData.width)
}

// repeated .RectData.ObjectParam object_parameter = 3;
inline int PictureData::object_parameter_size() const {
  return object_parameter_.size();
}
inline void PictureData::clear_object_parameter() {
  object_parameter_.Clear();
}
inline const ::RectData::ObjectParam& PictureData::object_parameter(int index) const {
  // @@protoc_insertion_point(field_get:RectData.PictureData.object_parameter)
  return object_parameter_.Get(index);
}
inline ::RectData::ObjectParam* PictureData::mutable_object_parameter(int index) {
  // @@protoc_insertion_point(field_mutable:RectData.PictureData.object_parameter)
  return object_parameter_.Mutable(index);
}
inline ::RectData::ObjectParam* PictureData::add_object_parameter() {
  // @@protoc_insertion_point(field_add:RectData.PictureData.object_parameter)
  return object_parameter_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::RectData::ObjectParam >&
PictureData::object_parameter() const {
  // @@protoc_insertion_point(field_list:RectData.PictureData.object_parameter)
  return object_parameter_;
}
inline ::google::protobuf::RepeatedPtrField< ::RectData::ObjectParam >*
PictureData::mutable_object_parameter() {
  // @@protoc_insertion_point(field_mutable_list:RectData.PictureData.object_parameter)
  return &object_parameter_;
}

// -------------------------------------------------------------------

// ObjectParam

// repeated string tag = 1;
inline int ObjectParam::tag_size() const {
  return tag_.size();
}
inline void ObjectParam::clear_tag() {
  tag_.Clear();
}
inline const ::std::string& ObjectParam::tag(int index) const {
  // @@protoc_insertion_point(field_get:RectData.ObjectParam.tag)
  return tag_.Get(index);
}
inline ::std::string* ObjectParam::mutable_tag(int index) {
  // @@protoc_insertion_point(field_mutable:RectData.ObjectParam.tag)
  return tag_.Mutable(index);
}
inline void ObjectParam::set_tag(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:RectData.ObjectParam.tag)
  tag_.Mutable(index)->assign(value);
}
inline void ObjectParam::set_tag(int index, const char* value) {
  tag_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:RectData.ObjectParam.tag)
}
inline void ObjectParam::set_tag(int index, const char* value, size_t size) {
  tag_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:RectData.ObjectParam.tag)
}
inline ::std::string* ObjectParam::add_tag() {
  return tag_.Add();
}
inline void ObjectParam::add_tag(const ::std::string& value) {
  tag_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:RectData.ObjectParam.tag)
}
inline void ObjectParam::add_tag(const char* value) {
  tag_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:RectData.ObjectParam.tag)
}
inline void ObjectParam::add_tag(const char* value, size_t size) {
  tag_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:RectData.ObjectParam.tag)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
ObjectParam::tag() const {
  // @@protoc_insertion_point(field_list:RectData.ObjectParam.tag)
  return tag_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
ObjectParam::mutable_tag() {
  // @@protoc_insertion_point(field_mutable_list:RectData.ObjectParam.tag)
  return &tag_;
}

// required int32 xmin = 2;
inline bool ObjectParam::has_xmin() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ObjectParam::set_has_xmin() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ObjectParam::clear_has_xmin() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ObjectParam::clear_xmin() {
  xmin_ = 0;
  clear_has_xmin();
}
inline ::google::protobuf::int32 ObjectParam::xmin() const {
  // @@protoc_insertion_point(field_get:RectData.ObjectParam.xmin)
  return xmin_;
}
inline void ObjectParam::set_xmin(::google::protobuf::int32 value) {
  set_has_xmin();
  xmin_ = value;
  // @@protoc_insertion_point(field_set:RectData.ObjectParam.xmin)
}

// required int32 ymin = 3;
inline bool ObjectParam::has_ymin() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ObjectParam::set_has_ymin() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ObjectParam::clear_has_ymin() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ObjectParam::clear_ymin() {
  ymin_ = 0;
  clear_has_ymin();
}
inline ::google::protobuf::int32 ObjectParam::ymin() const {
  // @@protoc_insertion_point(field_get:RectData.ObjectParam.ymin)
  return ymin_;
}
inline void ObjectParam::set_ymin(::google::protobuf::int32 value) {
  set_has_ymin();
  ymin_ = value;
  // @@protoc_insertion_point(field_set:RectData.ObjectParam.ymin)
}

// required int32 xmax = 4;
inline bool ObjectParam::has_xmax() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ObjectParam::set_has_xmax() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ObjectParam::clear_has_xmax() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ObjectParam::clear_xmax() {
  xmax_ = 0;
  clear_has_xmax();
}
inline ::google::protobuf::int32 ObjectParam::xmax() const {
  // @@protoc_insertion_point(field_get:RectData.ObjectParam.xmax)
  return xmax_;
}
inline void ObjectParam::set_xmax(::google::protobuf::int32 value) {
  set_has_xmax();
  xmax_ = value;
  // @@protoc_insertion_point(field_set:RectData.ObjectParam.xmax)
}

// required int32 ymax = 5;
inline bool ObjectParam::has_ymax() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ObjectParam::set_has_ymax() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ObjectParam::clear_has_ymax() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ObjectParam::clear_ymax() {
  ymax_ = 0;
  clear_has_ymax();
}
inline ::google::protobuf::int32 ObjectParam::ymax() const {
  // @@protoc_insertion_point(field_get:RectData.ObjectParam.ymax)
  return ymax_;
}
inline void ObjectParam::set_ymax(::google::protobuf::int32 value) {
  set_has_ymax();
  ymax_ = value;
  // @@protoc_insertion_point(field_set:RectData.ObjectParam.ymax)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace RectData

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_data_2eproto__INCLUDED
